### ISSUE TITLE
Docker conversion file owners

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/0-hub#45]
When converting a docker to a flist all files and folders are owned by root. While in the docker some folders and files are not owned by root.
Example: 
The folder `/tobias` and the file `/tobias/test.tobias` are owned by the user `tobias` in the docker but not in the flist.
jimbersoftware/test:0.1
https://hub.grid.tf/tobias.3bot/jimbersoftware-test-0.1.flist

The user `tobias` is listed in the /etc/passwd file of the flist

**Comment by maxux** [comment]
After investigation, using playground.hub.grid.tf which use latest code, everything is okay.
The production hub.grid.tf doesn't have this feature yet, I'll update it anytime soon.

About the difference of `Data` ownership, this is caused by volumes. This directory is a volume and `docker export` doesn't follow volumes (and thus permissions) since it use underlaying directory.

The `documentserver` is well set as `106/108` which is `ds/ds` according to passwd from the container.
