### ISSUE TITLE
group: create a way to have a kind of tags

### ISSUE THREAD

**Issue by maxux** [threefoldtech/0-hub#69]
Think about a way to group flist by tags and easily manage that. More will come soon.

**Comment by muhamadazmy** [comment]
This is needed to implement https://github.com/threefoldtech/zos/issues/2026 

The idea is that when publishing an flist to a repo, it can also given a `tag` or `group` name. All flists that are uploaded with the same group will then appear on the hub as if they are in the same sub directory on the repo. 

The use case in zos is to have all flists related to a single release version can be grouped together in one group, this allows to have consistent builds, and cleaner way to move the same version on multiple networks. 

It's also required that we support symlinks to a group. This means that an flist here https://hub.grid.tf/tf-zos can point to a group rather than a single flist.

> May be a group can be only symlinked to a group, and an flist only to an flist. this means that `zos:production` under tf-zos repo itself is a group but symlinks to tf-autobuild/v3.4.5 group.

**Comment by maxux** [comment]
Implemented via #70
